spring:
  application:
    name: withdrawal
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: amount-withdrawal-event
      isolation-level: read_committed
      properties:
        spring:
          json:
            trusted:
              packages: org.microservice.*

server:
  port: 0
